# Site settings
author: Ben
title: Soundwood Blog
header-img: img/home-bg.png
email: j.benhogan@gmail.com
copyright_name: Ben
description: > # this means to ignore newlines until "baseurl:"
  First Prompt
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Soundwood

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
